from .base import VariableLengthModelForPrediction, VariableLengthClassifierOutput
from .text import VariableLengthModelForPrediction
from .image import VariableLengthResNetForImageClassification

MODELS = VariableLengthModelForPrediction.registry